# Generated by Django 3.0.3 on 2021-09-06 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catagory', '0001_initial'),
        ('technology', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Technology',
        ),
    ]
