# Generated by Django 3.0.3 on 2021-09-07 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technology', '0002_auto_20210906_1423'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technology',
            options={'verbose_name': 'technology', 'verbose_name_plural': 'technologies'},
        ),
    ]
