# Generated by Django 3.0.3 on 2021-09-07 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catagory', '0002_aboutme'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutMe',
        ),
    ]
